services:
  pixman:
    image: pixman/pixman
    restart: always
    container_name: pixman
    environment:
      - http_proxy=http://192.168.50.50:7890
      - https_proxy=http://192.168.50.50:7890
      - MYTVSUPER_TOKEN=YOUR_TOKEN
      - HAMI_SESSION_ID=YOUR_SESSION_ID
      - HAMI_SERIAL_NO=YOUR_SERIAL_NO
      - HAMI_SESSION_IP=YOUR_SESSION_IP
    ports:
      - 5050:5000
